"""add documents.search_vector generated column

Revision ID: 206378bf403d
Revises: fb09a8d141d8
Create Date: 2026-07-22 03:17:10.854144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '206378bf403d'
down_revision: Union[str, Sequence[str], None] = 'fb09a8d141d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', filename)", persisted=True), nullable=True))
    op.create_index('ix_documents_search_vector', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_search_vector', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'search_vector')
    # ### end Alembic commands ###
