"""add risk_reviews and risk_flags

Revision ID: a4c5a364f72e
Revises: c19cf09d49f7
Create Date: 2026-08-09 09:46:52.813637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4c5a364f72e'
down_revision: Union[str, Sequence[str], None] = 'c19cf09d49f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('risk_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='risk_review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_reviews_document_id', 'risk_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_risk_reviews_document_version_id'), 'risk_reviews', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_risk_reviews_org_id'), 'risk_reviews', ['org_id'], unique=False)
    op.create_table('risk_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_review_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('auto_renewal', 'liability_cap', 'termination_terms', 'indemnification', 'governing_law', 'confidentiality_scope', name='risk_category'), nullable=False),
    sa.Column('verdict', sa.Enum('flagged', 'cleared', 'unable_to_verify', name='risk_verdict'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_review_id'], ['risk_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_flags_org_id'), 'risk_flags', ['org_id'], unique=False)
    op.create_index('ix_risk_flags_risk_review_id', 'risk_flags', ['risk_review_id'], unique=False)
    # NOTE: the autogenerated diff also included a drop_index on
    # ix_chunks_content_tsvector -- deliberately removed. That's a false
    # positive caused by the Chunk model never declaring that GIN index in
    # __table_args__ (it was added via a hand-written B2 migration), not an
    # actual intended change. Same class of generated-column/model drift
    # already seen in B2/B3. See B4 decisions log.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_risk_flags_risk_review_id', table_name='risk_flags')
    op.drop_index(op.f('ix_risk_flags_org_id'), table_name='risk_flags')
    op.drop_table('risk_flags')
    op.drop_index(op.f('ix_risk_reviews_org_id'), table_name='risk_reviews')
    op.drop_index(op.f('ix_risk_reviews_document_version_id'), table_name='risk_reviews')
    op.drop_index('ix_risk_reviews_document_id', table_name='risk_reviews')
    op.drop_table('risk_reviews')