"""add file_hash and parse_error to document_versions, char offsets to chunks

Revision ID: c04a88470ddf
Revises: a00750f22606
Create Date: 2026-07-21 08:58:48.942982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04a88470ddf'
down_revision: Union[str, Sequence[str], None] = 'a00750f22606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('char_start', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('char_end', sa.Integer(), nullable=False))
    op.add_column('document_versions', sa.Column('file_hash', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('parse_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_document_versions_file_hash'), 'document_versions', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_file_hash'), table_name='document_versions')
    op.drop_column('document_versions', 'parse_error')
    op.drop_column('document_versions', 'file_hash')
    op.drop_column('chunks', 'char_end')
    op.drop_column('chunks', 'char_start')
    # ### end Alembic commands ###
